### ISSUE TITLE
Decryption not working.

### ISSUE THREAD

**Issue by n0leptr** [Izumiko/hugo-encrypt#5]
After running password protected pages through this, the Decrypt button that is generated is not actually functioning. I see the SHA hashes being generated on the appropriate pages so I know it's processing the pages correctly, it just won't actually allow a user to decrypt.

**Comment by Izumiko** [comment]
In the latest commit, I use WebCrypto API instead of CryptoJS to decrypt the pages.  Maybe you can try to revert the commit to see if it works.

**Comment by n0leptr** [comment]
Closing this issue, since it's not being addressed.
